### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by hugovk** [beaugunderson/tracery-writer#2]
Cloning this repo and opening in a browser, I get this in the console:
```
file:///tmp/tracery-writer/tracery-writer-bundle.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///tmp/tracery-writer/codemirror.css Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///tmp/tracery-writer/lint.css Failed to load resource: net::ERR_FILE_NOT_FOUND
```

The first is missing and the second two are symbolic links to files inside node_modules/ which can't be found.

If I delete the symbolic link files, I can wget them all from https://beaugunderson.com/tracery-writer/* and it works.

**Comment by beaugunderson** [comment]
@hugovk just to verify; is this an issue after running `npm install`?

**Comment by beaugunderson** [comment]
oh, also, the bundle.js is generated with `npm run bundle`; but you'll also need to `npm install browserify` first for that step.

if you just want to run locally you can run `npm start` :)

(thanks for the report though, it's clear I need to document how to get started with the project!)

**Comment by hugovk** [comment]
Thanks, works perfectly with those steps :)

Yep, those in the readme'd be great!
